name: "Tests"

on: [pull_request]
jobs:
  lint:
    name: Tests ${{ matrix.php-versions }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['8.3', '8.4', '8.5']

    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # ratchet:actions/checkout@v6

      - name: Setup PHP ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # ratchet:shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: phpunit

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Compose install
        run: composer install --ignore-platform-reqs

      - name: Run tests
        run: composer test
